@startuml diagrammaDelleAttivita.puml

start

:Utente clicca "Fai entrare un auto";
:postoTrovato = false;

while (Per ogni elemento 'i' nell'array parcheggio)
    while (parcheggio[i] == 0) is (Sì, posto libero)
        :parcheggio[i] == 1 (Diventa occupato);
        :postoTrovato = true;
        :alert("Auto parcheggiata al posto" + (i+1));
    endwhile (No, già occupato)
        :Passa al prossimo "i";
endwhile
if (postoTrovato == false?)


stop

@enduml